### ISSUE TITLE
image fails to run on Mac OSX 10.9

### ISSUE THREAD

**Issue by vifino** [torch/image#16]
I was trying to use the image library, but this happens:

```
➜  ~  th -limage
> image.lena()
Wrong JPEG library version: library is 80, caller expects 62
/usr/local/share/lua/5.1/image/init.lua:115: attempt to index local 'a' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/image/init.lua:115: in function 'loader'
	/usr/local/share/lua/5.1/image/init.lua:247: in function 'load'
	/usr/local/share/lua/5.1/image/init.lua:1007: in function 'f'
	[string "local f = function() return image.lena() end ..."]:1: in main chunk
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/trepl/init.lua:510: in function </usr/local/share/lua/5.1/trepl/init.lua:452>	
> 
```

I have no idea how to fix that.

**Comment by marcinic** [comment]
I had a similar problem. Upgrading lua to 5.2.3 solved it for me.

**Comment by lefromage** [comment]
issue still there on MacOS Yosemite
th -limage -e "image.lena()"
Wrong JPEG library version: library is 80, caller expects 62

**Comment by arashilen** [comment]
I had same problem in 10.10.2, and I try to upgrade the lua to Lua 5.3.0 to solve it, but the torch still run version 5.1.

**Comment by Atcold** [comment]
I have the latest version of everything (`brew`, `libjpg` and `image`) and everything works just fine.
I guess we can close this issue.

**Comment by leocck** [comment]
After trying many things, I solved this in torch only using PNG files

**Comment by nessig** [comment]
> -- Found JPEG: /Users/bakercp/anaconda/lib/libjpeg.dylib  
> -- Found ZLIB: /Users/bakercp/anaconda/lib/libz.dylib (found version "1.2.8") 
> -- Found PNG: /Users/bakercp/anaconda/lib/libpng.dylib (found version "1.5.18") 
Pretty much what happened to me except it was getting built with my Postgres' libjpef.dylib. I just went into my bash profile and took that off my path where I was exporting it, then rebuilt with `luarocks install image`, and it worked after that! Check the logs when you run `luarocks install image` because thats where I was it was using a possibly out of date version of libjpeg. Strangely, my anaconda's libjpeg.dylib (which it linked too after I changed my PATH) works fine and built image without any problems.

**Comment by adam-erickson** [comment]
The solution of @JohnZed worked for me. This JPEG library was installed with GDAL and caused a conflict. Simply deleting it fixed the issue.

**Comment by ramsingla** [comment]
On my mac system the following solved the issue.

```brew install homebrew/versions/jpeg6b
brew unlink jpeg
brew link homebrew/versions/jpeg6b
luarocks install image
```

after this the following command runs without issue

`th -limage -e "image.lena()"`

**Comment by hassanshallal** [comment]
hi guys, i am sure this is so redundant but I have no other choice but bringing up the issue and asking for help as of how to deal with it. 
So, when I try image.lena(), I get this typical error:
Wrong JPEG library version: library is 80, caller expects 90

Now, as far as i understood from this and so many other posts, there is some sort of conflict, I used JohnZed's feedback above and found that I have so many versions of lipjpeg, here is what I have:
find /usr/ /Library/ /opt/ /lib/ -iname "libjpeg*.dylib" 2>/dev/null 
the above gives the following output:

/usr//local/Cellar/jpeg/8d/lib/libjpeg.8.dylib
/usr//local/Cellar/jpeg/8d/lib/libjpeg.dylib
/usr//local/Cellar/jpeg9/lib/libjpeg.9.dylib
/usr//local/Cellar/jpeg9/lib/libjpeg.dylib
/usr//local/mac-dev-env/libjpeg-9b/lib/libjpeg.9.dylib
/usr//local/mac-dev-env/libjpeg-9b/lib/libjpeg.dylib
/usr//local/octave/3.8.0/lib/libjpeg.9.dylib
/usr//local/octave/3.8.0/lib/libjpeg.dylib
/Library//Frameworks/GTK+.framework/Versions/2.24.X11/Resources/lib/libjpeg.9.dylib
/Library//Frameworks/GTK+.framework/Versions/2.24.X11/Resources/lib/libjpeg.dylib
/Library//Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/lib/libjpeg.dylib
/Library//Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/libjpeg.dylib

Before I go ahead and delete or modify any of the above versions, what would be the best approach to solve this problem? 

Thanks a lot

**Comment by davidavdav** [comment]
For me, I ran into similar problems with 
```sh 
luajit -limage -e "image.test()"
seed: 	1493905914
Running 41 tests
 1/41 CompressAndDecompress ............................................. [PASS]
 2/41 test_transformation_largeByteImage_vflip .......................... [PASS]
 3/41 CompressAndDecompressPNG .......................................... [WAIT]libpng warning: Application built with libpng-1.4.12 but running with 1.6.29
 3/41 CompressAndDecompressPNG .......................................... [ERROR]

...

CompressAndDecompressPNG
 Function call failed
/Users/david/src/torch/install/share/lua/5.1/image/init.lua:215: [write_png_file] png_create_write_struct failed
stack traceback:
	[C]: in function 'save'
	/Users/david/src/torch/install/share/lua/5.1/image/init.lua:215: in function 'compressPNG'
	/Users/david/src/torch/install/share/lua/5.1/image/test.lua:419: in function </Users/david/src/torch/install/share/lua/5.1/image/test.lua:416>
	[C]: in function 'xpcall'
	...s/david/src/torch/install/share/lua/5.1/torch/Tester.lua:477: in function '_pcall'
	...s/david/src/torch/install/share/lua/5.1/torch/Tester.lua:436: in function '_run'
	...s/david/src/torch/install/share/lua/5.1/torch/Tester.lua:355: in function 'run'
	/Users/david/src/torch/install/share/lua/5.1/image/test.lua:708: in function 'test'
	(command line):1: in main chunk
	[C]: at 0x010d8e6a00
```
which was finally resolved by following @JohnZed suggestion: search for stray libjpg files, and re-build `luarocks install image`.  In my case, I had an unused old Mono.Framework on the system.

**Comment by tailsu** [comment]
Mono.framework causes CMake to produce an incorrect build due to libpng and libjpeg.

CMake has this funny parameter called [CMAKE_FIND_FRAMEWORK](https://cmake.org/cmake/help/v3.4/variable/CMAKE_FIND_FRAMEWORK.html) which is set by default to FIRST. This means that CMake will first look for files first in all framework directories, and only then in regular include directories. Funnily enough Mono.framework contains the headers for libjpeg and libpng. So, CMake finds the headers in Mono, but the library in the regular install location, e.g. /usr/local/lib and therefore a version mismatch happens.

Mono is a known menace (for some time `brew doctor` warned if Mono is installed that builds may fail). You can see this behavior if you create a CMakeLists.txt file with the single line `find_package(JPEG)`, run `cmake .` and take a look at the paths in the generated CMakeCache.txt file.

The fix that definitively worked for me was to check out the project manually, add `set(CMAKE_FIND_FRAMEWORK LAST)` to CMakeLists.txt before the `find_package` calls and then run `luarocks make`. This way CMake found the headers in the right folder.
