### ISSUE TITLE
undefined symbol: GOMP_parallel

### ISSUE THREAD

**Issue by RobertArbon** [torch/image#207]
Hi, 

I've just done a fresh install of Torch (along with Cuda 8.0 and cuDNN and MKL Blas on Ubuntu 16.04) and image doesn't want to load:

th> require 'image'
/home/robert/torch/install/share/lua/5.1/trepl/init.lua:389: /home/robert/torch/install/share/lua/5.1/trepl/init.lua:389: ...e/robert/torch/install/share/lua/5.1/luarocks/loader.lua:117: error loading module 'libimage' from file '/home/robert/torch/install/lib/lua/5.1/libimage.so':
	/home/robert/torch/install/lib/lua/5.1/libimage.so: undefined symbol: GOMP_parallel
stack traceback:
	[C]: in function 'error'
	/home/robert/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	[string "_RESULT={require 'image'}"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/robert/torch/install/share/lua/5.1/trepl/init.lua:661: in function 'repl'
	...bert/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00405d50	

I tried adding '-DWITH_OPENMP=OFF' to the rockspec but that doesn't seem to have helped.  

Any idea what's going on?

Thanks!

**Comment by RobertArbon** [comment]
the image package works after a fresh installation of Torch but not when you install it/update it when Torch is installed.

**Comment by MrZoidberg** [comment]
any ways to fix this?

**Comment by RobertArbon** [comment]
I got it to work, why not, by installing Torch but not updating the Image module.  Torch7 comes with Image as standard.

**Comment by soumith** [comment]
i've not been able to reproduce this, unfortunately.
Are you by any chance having anaconda in your $PATH or $LD_LIBRARY_PATH, and anaconda has libgcc installed? That might explain it, because anaconda's libgcc has OMP of a different version than what your system compiler has.
With a default torch install, we explicitly scrub anaconda from the PATH before proceeding: https://github.com/torch/distro/blob/master/install.sh#L31-L36

**Comment by isomerase** [comment]
@soumith I'm experiencing this problem and I have anaconda in my $PATH. Is there a work-around? I just cloned `jcjohnson/fast-neural-style/` and I'm trying to run their torch script.

**Comment by panfengli** [comment]
I encountered the same problem twice. First time on a desktop, I tried every method, uninstalled and reinstalled torch again and again, but no one worked. So I gave up, I uninstalled Ubuntu, then it was fine.

Today I meet with this problem again on my labtop, I also have anaconda installed already. I deleted torch, reinstall, use luarocks to install image package, still not work. I thought maybe it is due to the uncomplete removing of torch, so I look into torch folder, I run `update.sh`, then hope to see a good result. Unfortunately, error comes again when I `require 'nn'`. But it is a simple one, I just `luarocks install torch`, then `luarocks install image`, then things go well. 

I don't know whether it is a general problem, but maybe you can try the `clean.sh` and `updata.sh` when you want to delete torch and reinstall it. By the way, I didn't remove anaconda, and I also run `conda install -y gcc` before I run `update.sh`, seeing from [conda install -y gcc](url)
