### ISSUE TITLE
JPEG error handligh

### ISSUE THREAD

**Issue by Atcold** [torch/image#59]
If an image is corrupted, `image.load()` does not shoot an error but outputs a string.
```lua
th> image.load(p)
Empty input file
```
I couldn't track down where the `Empty input file` string is outputted, therefore I guess it's coming from `libjpeg` and how it's handled in [generic/jpeg.c](https://github.com/torch/image/blob/master/generic/jpeg.c).

**Comment by soumith** [comment]
I'm closing this issue. I am not sure what you are trying to report here. Seems okay to me.

**Comment by Atcold** [comment]
The problem is that `image.loadJPG()` does not issue an error if the file is empty / corrupted. It simply read trash. Instead, it should throw an error.

**Comment by deltheil** [comment]
> Instead, it should throw an error

Since #58 has been merged it raises an error, right? e.g.:

```Lua
require 'image'

local ok, img = pcall(image.load, 'void.jpg')
if not ok then
  print('[error] `' .. img .. '`')
end
```

This gives:

```
Empty input file
[error] `/usr/local/share/lua/5.1/image/init.lua:142: cannot open file for reading`
```

With a corrupted JPEG it gives something like:

```
Corrupt JPEG data: 2365 extraneous bytes before marker 0x4c
Unsupported marker type 0x4c
```

In both cases this message comes from libjpeg and is written on `stderr` via `fprintf` by the [error callback](https://github.com/torch/image/blob/1f551bb/generic/jpeg.c#L66-L68).
